version: "3.7"

services:
  envoy:
    image: envoyproxy/envoy:v1.13.0
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - 10000:10000
    depends_on:
      - app

  app:
    image: nginx:latest
  
  ext-authz:
    image: hanjunlee/ext-authz
    command: 
      - --token
      - foo
